version: "3.9"

services:
  go-app:
    container_name: go-app
    image: go-api-tutorial
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=go_db
    depends_on:
      - go_db
  go_db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: {}